import 'server-only';
import JSZip from 'jszip';

import { toGenotype } from './genome';
import { findFont, readFontFile } from './store';
import type { FontRecord, GlyphSetName } from './types';

/**
 * A downloadable type kit — the deliverable, not just two loose TTFs.
 *
 * A designer who likes a pair should be able to take it away as one file that
 * drops into a project: the fonts, a wired @font-face stylesheet, a README that
 * is itself the specimen, and an honest provenance notice.
 */
export type KitEntry = {
  role: 'display' | 'text' | 'font';
  record: FontRecord;
  glyphSet: GlyphSetName;
  ttf: Buffer;
};

/**
 * Resolve a font to a kit entry with its best available cut (extended if it's
 * been promoted, else the standard 72-glyph set). Returns null if not ready.
 */
export async function gatherKitEntry(
  runId: string,
  fontId: string,
  role: KitEntry['role'],
): Promise<KitEntry | null> {
  const record = await findFont(runId, fontId);
  if (!record || record.status !== 'ready') return null;
  const glyphSet: GlyphSetName = record.extended?.status === 'ready' ? 'extended' : 'standard';
  const ttf = await readFontFile(record.id, glyphSet);
  if (!ttf) return null;
  return { role, record, glyphSet, ttf };
}

const safeFile = (name: string) =>
  name
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase() || 'font';

export async function buildKit(
  title: string,
  entries: KitEntry[],
): Promise<{ zip: Buffer; filename: string }> {
  const zip = new JSZip();
  const fontsDir = zip.folder('fonts')!;

  const faceRules: string[] = [];
  const usageRules: string[] = [];
  const readmeFonts: string[] = [];

  for (const e of entries) {
    const family = e.record.name;
    const file = `${safeFile(family)}${e.glyphSet === 'extended' ? '-extended' : ''}.ttf`;
    fontsDir.file(file, e.ttf);

    faceRules.push(
      `@font-face {\n` +
        `  font-family: "${family}";\n` +
        `  src: url("fonts/${file}") format("truetype");\n` +
        `  font-display: swap;\n` +
        `}`,
    );
    const cls = e.role === 'text' ? 'body' : e.role === 'display' ? 'display' : safeFile(family);
    usageRules.push(`.${cls} { font-family: "${family}", serif; }`);

    readmeFonts.push(
      `  ${e.role.toUpperCase().padEnd(8)}${family}\n` +
        `    ${toGenotype(e.record.genome)}\n` +
        `    glyph set: ${e.glyphSet === 'extended' ? '319 — extended Latin (accents, curly quotes, dashes)' : '72 — basic Latin only'}\n` +
        `    file: fonts/${file}`,
    );
  }

  const css =
    `/* ${title} — generated by Foundry · https://fonts.mili.dev */\n\n` +
    `${faceRules.join('\n\n')}\n\n` +
    `/* usage */\n${usageRules.join('\n')}\n`;
  zip.file('foundry.css', css);

  const display = entries.find((e) => e.role === 'display');
  const text = entries.find((e) => e.role === 'text');
  const rule = '='.repeat(Math.min(title.length, 60));

  const usage =
    entries.length === 2 && display && text
      ? [
          `  3. Set headlines in "${display.record.name}" (the display face) and running`,
          `     text in "${text.record.name}" (the text face).`,
        ]
      : [`  3. Use font-family "${entries[0]?.record.name}".`];

  const anyBasic = entries.some((e) => e.glyphSet === 'standard');
  const readme = [
    title,
    rule,
    '',
    'Generated with Foundry (https://fonts.mili.dev) using the Mixfont API.',
    '',
    'FONTS',
    ...readmeFonts,
    '',
    'HOW TO USE',
    '  1. Copy the fonts/ folder and foundry.css into your project.',
    '  2. Link foundry.css — it declares the @font-face rules.',
    ...usage,
    '',
    ...(anyBasic
      ? [
          'NOTE',
          '  One or more faces are the 72-glyph basic-Latin cut — no accented',
          '  characters, curly quotes, or en/em dashes. Promote to the 319-glyph',
          '  extended set in Foundry before shipping to clients who need them.',
          '',
        ]
      : []),
    'See NOTICE.txt for provenance and licensing.',
    '',
  ].join('\n');
  zip.file('README.txt', readme);

  const notice = [
    'NOTICE',
    '',
    'The font files in this kit were generated on demand via the Mixfont font-',
    'generation API (https://www.mixfont.com) from prompts describing each',
    "typeface's design. They are your generated output.",
    '',
    'For the terms that govern use of fonts produced by the Mixfont API, see',
    "Mixfont's own documentation and terms at https://www.mixfont.com — that is",
    'the authoritative source. Foundry neither grants nor restricts rights in the',
    'generated fonts.',
    '',
    'foundry.css, README.txt, and this notice are provided as-is, without warranty.',
    'Foundry itself is open source (MIT): https://github.com/jmilinovich/foundry',
    '',
  ].join('\n');
  zip.file('NOTICE.txt', notice);

  const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  return { zip: buf, filename: `${safeFile(title)}.zip` };
}
